-- Link codes a patient stranger could guess (QA #8).
--
-- The code was `lpad(floor(random() * 1000000)::text, 6, '0')`: one of a
-- million values, live for fifteen minutes, checked against every unlinked
-- sender who messages the bot. Two problems, and the smaller one is the
-- million.
--
-- `random()` is a pseudo-random number generator seeded per session, not a
-- cryptographic one. Its output is not meant to be unguessable, and a code
-- drawn from it is not either -- so "one in a million per attempt" was already
-- an optimistic way to describe it.
--
-- The webhook secret does not help here. It stops a forged HTTP request, and
-- these are genuine Telegram messages from an attacker's own account: they
-- arrive with a valid secret header because Telegram put it there. Nothing in
-- the application counted a failed attempt, so the only limit was how fast
-- Telegram would deliver messages, for the whole fifteen minutes.
--
-- Two changes. The token gets large enough that guessing stops being a
-- strategy, and failures get counted so that trying anyway is visible and
-- bounded.

-- 1. A token from a cryptographic source.
--
-- gen_random_uuid() is core since PostgreSQL 13 and draws from
-- pg_strong_random(), i.e. the OS CSPRNG -- deliberately NOT pgcrypto's
-- gen_random_bytes(), which would be equally good and is an extension living
-- in a non-default schema on this project, so a fresh database built from this
-- repository might not have it. A token this function cannot generate is worse
-- than one that is four characters longer.
--
-- 32 hex characters, ~122 bits. Nobody types it: Settings shows it to be
-- copied, and it is short enough to also travel as a Telegram deep-link
-- payload (max 64 characters) if one is ever wired up.
create or replace function generate_telegram_link_code(p_member_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_household_id uuid;
begin
  select household_id into v_household_id from household_members where id = p_member_id;
  if v_household_id is null or not is_household_member(v_household_id) then
    raise exception 'not a member of this household' using errcode = '42501';
  end if;

  v_code := replace(gen_random_uuid()::text, '-', '');

  perform set_config('app.bypass_telegram_link_guard', 'on', true);
  update household_members
    set telegram_link_code = v_code,
        telegram_link_code_expires_at = now() + interval '15 minutes'
    where id = p_member_id;

  return v_code;
end;
$$;

revoke execute on function generate_telegram_link_code(uuid) from public, anon;

comment on column household_members.telegram_link_code is
  'One-time token generated by generate_telegram_link_code(), redeemed by sending it to the bot. 32 hex characters from gen_random_uuid(), which draws from the OS CSPRNG -- it was six digits from random(), which is a PRNG and guessable within its fifteen-minute life (QA #8). Cleared on redemption or expiry.';

-- 2. Failures, counted.
--
-- Defence in depth rather than the main control: with the token above, an
-- attacker guessing at Telegram's delivery rate for the full fifteen minutes
-- has odds that do not round away from zero. This exists because "the token is
-- long" is an argument, and a counter is a fact -- and because it turns an
-- attempt from invisible into something that happened and was refused.
--
-- One row per failed attempt by an unlinked sender. Only failures: a
-- successful link clears the sender's rows, so an ordinary member who mistypes
-- once and then succeeds leaves nothing behind.
create table telegram_link_attempts (
  id bigint generated always as identity primary key,
  telegram_user_id bigint not null,
  attempted_at timestamptz not null default now()
);

comment on table telegram_link_attempts is
  'Failed link-token attempts by unlinked Telegram senders, used to rate-limit guessing (QA #8). Cleared for a sender on a successful link; pruned to 24 hours by the daily run_recurring_check pass.';

-- Serves the per-sender window check.
create index telegram_link_attempts_sender_idx on telegram_link_attempts (telegram_user_id, attempted_at desc);
-- Serves the global window check and the daily prune.
create index telegram_link_attempts_time_idx on telegram_link_attempts (attempted_at desc);

alter table telegram_link_attempts enable row level security;

-- No policies, deliberately, and for the same reason as telegram_update_log:
-- a failed attempt belongs to the bot, not to a household. The sender is by
-- definition not linked to one, so there is no household this row could be
-- scoped to and no member it would be right to show it to. service_role (the
-- webhook) bypasses RLS; everyone else sees nothing, which is the whole intent.
