-- SHR-236: link a household member to a Telegram account, and guard the
-- link fields against being set by an ordinary client update. The existing
-- "members can update household roster" RLS policy allows any household
-- member to update any column on any member's row (needed for renames/role
-- changes) -- without a guard, that same policy would let one member set
-- telegram_user_id on ANY row, including their own to someone else's
-- identity or another member's to hijack it. RLS operates at the row level,
-- not the column level, so the guard has to be a trigger.
alter table household_members
  add column telegram_user_id bigint unique,
  add column telegram_link_code text,
  add column telegram_link_code_expires_at timestamptz;

create or replace function guard_telegram_link_columns()
returns trigger
language plpgsql
as $$
begin
  if (new.telegram_user_id is distinct from old.telegram_user_id
      or new.telegram_link_code is distinct from old.telegram_link_code
      or new.telegram_link_code_expires_at is distinct from old.telegram_link_code_expires_at)
     and auth.role() <> 'service_role'
     and coalesce(current_setting('app.bypass_telegram_link_guard', true), 'off') <> 'on'
  then
    raise exception 'telegram link fields can only be changed by the linking flow' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger household_members_guard_telegram_link
  before update on household_members
  for each row execute function guard_telegram_link_columns();

-- Callable by any signed-in household member for their own household's
-- roster (matches the existing update policy's household-membership check),
-- but the actual column write is only permitted because of the local GUC
-- flag below -- the guard trigger still fires and would otherwise block it.
create or replace function generate_telegram_link_code(p_member_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_household_id uuid;
begin
  select household_id into v_household_id from household_members where id = p_member_id;
  if v_household_id is null or not is_household_member(v_household_id) then
    raise exception 'not a member of this household' using errcode = '42501';
  end if;

  v_code := lpad(floor(random() * 1000000)::text, 6, '0');

  perform set_config('app.bypass_telegram_link_guard', 'on', true);
  update household_members
    set telegram_link_code = v_code,
        telegram_link_code_expires_at = now() + interval '15 minutes'
    where id = p_member_id;

  return v_code;
end;
$$;

revoke execute on function generate_telegram_link_code(uuid) from public, anon;

comment on column household_members.telegram_user_id is 'Telegram numeric user id, set only by the telegram-webhook Edge Function redeeming a link code. Never client-writable directly (see guard_telegram_link_columns).';
comment on column household_members.telegram_link_code is 'One-time code generated by generate_telegram_link_code(), redeemed by sending it to the bot. Cleared on redemption or expiry.';
